services:
  chatbot:
    build: .
    container_name: chatbot
    image: telegram-chatbot-service
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./data/:/app/data/
      - ./logs/:/app/logs/
    
